/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react/prop-types */
/* eslint-disable no-unused-vars */
import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  FaChevronLeft,
  FaSignOutAlt,
  FaBookOpen,
  FaGraduationCap,
  FaCheckCircle,
  FaLayerGroup,
  FaClipboardList,
  FaLock,
  FaQuestionCircle,
  FaFileAlt,
  FaPencilAlt,
  FaLightbulb,
} from "react-icons/fa";
import { useGetQuizCompletionByStudentIdQuery } from "../../../services/QuizResponse/quizCompletionApi";
import EnhancedButton from "./EnhancedButton"; // Import the EnhancedButton component
import { useGetAssignmentCompletionByStudentIdQuery } from "../../../services/Assignment/assignmentCompletionApi";
import FeedBackModal from "../QuizContent/FeedBackModal"; // Fixed import path
import { useGetModuleFeedbackHistoryQuery } from "../../../services/Ai_performace_tracking/performanceFeedbackApi";
import { useGenerateFeedbackMutation } from "../../../services/Ai_performace_tracking/performanceTrackingApi";
import { getStudentToken } from "../../../services/CookieService";

import { isModuleReadyForFeedback } from "../../../utils/moduleFeedbackCheck";


const CourseSidebar = ({
  sidebarRef,
  sidebarWidth,
  sidebarCollapsed,
  toggleSidebar,
  sessionsData,
  activeSessionId,
  setActiveSessionId,
  modules,
  activeModuleId,
  setActiveModuleId,
  setNewModuleId,
  completedModules,
  topicData,
  activeTopic,
  setActiveTopic,
  activeTopicMaterial,
  setActiveTopicMaterial,
  handleTopicClick,
  completedTopics,
  setShowEndSessionModal,
  topicContentDataByModule,
  quizData = [],
  setActiveQuiz,
  courseTitle,
  userId,
  setIsQuizCompleted,
  assignmentData = [],
  setActiveAssignment,
  setIsAssignmentCompleted,
  access_token,
  setMaterialType,
  courseId,
}) => {
  // Local state for tooltip
  const [showTooltip, setShowTooltip] = useState(null);
  const [showFeedback, setShowFeedback] = useState(false);
  const [selectedModuleId, setSelectedModuleId] = useState(null);
  const [shouldAutoGenerateFeedback, setShouldAutoGenerateFeedback] = useState(false);
  const [hasAutoGeneratedFeedback, setHasAutoGeneratedFeedback] = useState(false);

  // Get access token
  // const { access_token } = getStudentToken();

  // Get quiz completion data
  const { data: quizCompletionData } = useGetQuizCompletionByStudentIdQuery(
    { userId, courseId },
    {
      skip: !userId,
    }
  );
  const {
    data: assignmentCompletionData,
    refetch: refetchAssignmentCompletion,
  } = useGetAssignmentCompletionByStudentIdQuery(
    { studentId: userId, access_token },
    {
      skip: !userId,
    }
  );

  // Get feedback history for the selected module
  const { data: feedbackHistory, refetch: refetchFeedbackHistory } = useGetModuleFeedbackHistoryQuery(
    { userId, moduleId: selectedModuleId, access_token },
    { skip: !selectedModuleId || !userId || !access_token || !showFeedback }
  );

  // Generate feedback mutation
  const [generateFeedback, { isLoading: isGeneratingFeedback }] = useGenerateFeedbackMutation();

  // Automatically open feedback modal when active module is ready for feedback
  useEffect(() => {
    const timeout = setTimeout(() => {
      if (
        activeModuleId &&
        modules &&
        modules.length > 0 &&
        quizData &&
        quizData.length > 0 &&
        completedTopics &&
        quizCompletionData &&
        topicData?.data?.[0]?.data?.length > 0
      ) {
        const activeModule = modules.find((m) => m.public_hash === activeModuleId);

        // ✅ Ensure the topicData actually belongs to this module (very important!)
        const topicDataModuleId = topicData?.data?.[0]?.data?.[0]?.module_id;
        if (!activeModule || topicDataModuleId !== activeModule.id) {
          return;
        }

        // ✅ Check if module is ready using shared utility
        const ready = isModuleReadyForFeedback(
          activeModule.id,
          topicData,
          quizData,
          completedTopics,
          quizCompletionData
        );

        if (ready) {
          setSelectedModuleId(activeModule.id);
          setShowFeedback(true);
        } else {
          console.log("Module is NOT ready for feedback:", activeModule.title);
        }
      }
    }, 1000); // slight delay to ensure data is fully updated

    return () => clearTimeout(timeout);
  }, [activeModuleId, completedTopics, quizData, quizCompletionData, topicData]);


  // Handle auto-generation of feedback when modal opens and no feedback exists
  useEffect(() => {
    if (showFeedback && selectedModuleId && feedbackHistory && !isGeneratingFeedback && !hasAutoGeneratedFeedback) {
      // Check if there's any existing feedback
      const hasExistingFeedback = feedbackHistory?.data && feedbackHistory.data.length > 0;

      // Don't auto-generate if feedback history is still loading or if feedback already exists
      if (!hasExistingFeedback && !shouldAutoGenerateFeedback && feedbackHistory !== undefined) {
        setShouldAutoGenerateFeedback(true);
        setHasAutoGeneratedFeedback(true); // Mark that we've started auto-generation

        // Auto-generate feedback
        generateFeedback({
          userId,
          moduleId: selectedModuleId,
          access_token,
        }).unwrap()
          .then(() => {
            window.dispatchEvent(new CustomEvent("FEEDBACK_GENERATED", {
              detail: { moduleId: selectedModuleId }
            }));
            refetchFeedbackHistory();
          })
          .catch((error) => {
            console.error("Failed to auto-generate feedback:", error);
            // Reset the flag on error so user can try again
            setHasAutoGeneratedFeedback(false);
            // Don't show error to user for auto-generation, just log it
          })
          .finally(() => {
            setShouldAutoGenerateFeedback(false);
          });
      }
    }
  }, [showFeedback, selectedModuleId, feedbackHistory, isGeneratingFeedback, shouldAutoGenerateFeedback, hasAutoGeneratedFeedback, generateFeedback, userId, access_token, refetchFeedbackHistory]);

  // Reset auto-generation flag when module changes
  useEffect(() => {
    setHasAutoGeneratedFeedback(false);
  }, [selectedModuleId]);

  // Reset auto-generation flag when feedback already exists
  useEffect(() => {
    if (feedbackHistory?.data && feedbackHistory.data.length > 0) {
      setHasAutoGeneratedFeedback(true); // Mark as already generated if feedback exists
    }
  }, [feedbackHistory]);

  // Check if a topic is completed
  const isTopicCompleted = (topicId) => {
    return completedTopics[topicId] === true || completedTopics[topicId] === 1;
  };

  // Helper function to get topic-associated quizzes
  const getTopicQuizzes = (topicId) => {
    if (
      !topicContentDataByModule?.data ||
      !topicId ||
      !Array.isArray(topicContentDataByModule.data)
    )
      return [];

    // Get all content items for this topic
    const topicContents =
      topicContentDataByModule.data[0]?.data?.filter(
        (content) => content.topic_id === topicId
      ) || [];

    const quizzes = [];

    // Process each content item for the topic
    topicContents.forEach((content) => {
      // Add quiz if exists
      if (content.quiz_id && Array.isArray(quizData)) {
        const quiz = quizData.find((q) => q.id === content.quiz_id);
        if (quiz) {
          quizzes.push({
            id: quiz.id,
            title: quiz.title,
            type: "quiz",
          });
        }
      }
    });

    return quizzes;
  };

  // Helper function to get topic-associated assignments
  const getTopicAssignments = (topicId) => {
    if (
      !topicContentDataByModule?.data ||
      !topicId ||
      !Array.isArray(topicContentDataByModule.data)
    )
      return [];

    // Get all content items for this topic
    const topicContents =
      topicContentDataByModule.data[0]?.data?.filter(
        (content) => content.topic_id === topicId
      ) || [];

    const assignments = [];

    // Process each content item for the topic
    topicContents.forEach((content) => {
      // Add assignment if exists
      if (content.assignment_id && Array.isArray(assignmentData)) {
        const assignment = assignmentData.find(
          (a) => a.id === content.assignment_id
        );
        if (assignment) {
          assignments.push({
            id: assignment.id,
            title: assignment.title,
            type: "assignment",
          });
        }
      }
    });

    return assignments;
  };

  // Updated function to handle topic quiz click
  const handleModuleQuizClick = (quiz, materialType) => {
    if (materialType === "topicMaterial") {
      // Set active material
      setActiveTopicMaterial({
        id: quiz.id,
        type: "quiz",
      });
    }
    setMaterialType(materialType);

    // Check if this is a topic quiz
    const isTopicQuiz = topicContentDataByModule?.data?.[0]?.data?.some(
      (content) => content.quiz_id === quiz.id
    );

    // Only clear active topic if it's a module quiz (not a topic quiz)
    if (!isTopicQuiz && setActiveTopic) {
      setActiveTopic(null);
    }

    if (setActiveQuiz) {
      // If it's a single quiz object (not an array)
      if (!Array.isArray(quiz)) {
        // Find completion data for this specific quiz
        const quizCompletion = quizCompletionData?.find(
          (completion) =>
            completion.quizId === quiz.id && completion.isCompleted === true
        );

        // Reset assignment state when switching to quiz
        if (setActiveAssignment) {
          setActiveAssignment(null);
        }
        if (setIsAssignmentCompleted) {
          setIsAssignmentCompleted(null);
        }

        // Reset completion status
        setIsQuizCompleted(null);

        // Set the active quiz with its completion data
        if (quizCompletion && quizCompletion.isCompleted === true) {
          setIsQuizCompleted(quizCompletion);
          // Pass the specific quiz completion data along with the quiz
          setActiveQuiz({
            ...quiz,
            completionData: quizCompletion,
          });
        } else {
          setActiveQuiz(quiz);
        }
      } else {
        // Reset assignment state when switching to quiz list
        if (setActiveAssignment) {
          setActiveAssignment(null);
        }
        if (setIsAssignmentCompleted) {
          setIsAssignmentCompleted(null);
        }
        setActiveQuiz(quiz);
      }
    }
  };

  // Updated function to handle module assignment click
  const handleModuleAssignmentClick = (assignment, materialType) => {
    if (materialType === "topicMaterial") {
      // Set active material
      setActiveTopicMaterial({
        id: assignment.id,
        type: "assignment",
      });
    }
    setMaterialType(materialType);

    // Check if this is a topic assignment
    const isTopicAssignment = topicContentDataByModule?.data?.[0]?.data?.some(
      (content) => content.assignment_id === assignment.id
    );

    // Only clear active topic if it's a module assignment (not a topic assignment)
    if (!isTopicAssignment && setActiveTopic) {
      setActiveTopic(null);
    }

    if (setActiveAssignment) {
      // If it's a single assignment object (not an array)
      if (!Array.isArray(assignment)) {
        // Find completion data for this specific quiz
        const assignmentCompletion = assignmentCompletionData?.find(
          (completion) =>
            completion.assignmentId === assignment.id && completion.isCompleted
        );

        // Reset quiz state when switching to assignment
        if (setActiveQuiz) {
          setActiveQuiz(null);
        }
        if (setIsQuizCompleted) {
          setIsQuizCompleted(null);
        }

        // Reset completion status
        setIsAssignmentCompleted(null);

        // Set the active quiz with its completion data
        if (assignmentCompletion && assignmentCompletion.isCompleted === true) {
          setIsAssignmentCompleted(assignmentCompletion);
          // Pass the specific assignment completion data along with the assignment
          setActiveAssignment({
            ...assignment,
            completionData: assignmentCompletion,
          });
        } else {
          setActiveAssignment(assignment);
        }
      } else {
        // Reset quiz state when switching to assignment list
        if (setActiveQuiz) {
          setActiveQuiz(null);
        }
        if (setIsQuizCompleted) {
          setIsQuizCompleted(null);
        }
        setActiveAssignment(assignment);
      }
    }
  };

  // Helper function to get module quizzes (excluding topic-associated quizzes and inactive quizzes)
  const getModuleQuizzes = (moduleId) => {
    if (
      !moduleId ||
      !Array.isArray(quizData) ||
      !topicContentDataByModule?.data
    )
      return [];

    // Get all quiz IDs that are associated with topics
    const topicAssociatedQuizIds = new Set(
      topicContentDataByModule.data[0]?.data
        ?.filter((content) => content.quiz_id !== null)
        .map((content) => content.quiz_id) || []
    );

    // Filter quizzes that are:
    // 1. In the current module
    // 2. Not associated with any topic
    // 3. Not inactive
    const moduleQuizzes = quizData.filter(
      (quiz) =>
        quiz.module_id === moduleId &&
        !topicAssociatedQuizIds.has(quiz.id) &&
        quiz.status !== "inactive"
    );

    return moduleQuizzes;
  };


  // Helper function to get module assignments (excluding topic-associated assignments and closed assignments)
  const getModuleAssignments = (moduleId) => {
    if (
      !moduleId ||
      !Array.isArray(assignmentData) ||
      !topicContentDataByModule?.data
    )
      return [];

    // Get all assignment IDs that are associated with topics
    const topicAssociatedAssignmentIds = new Set(
      topicContentDataByModule.data[0]?.data
        ?.filter((content) => content.assignment_id !== null)
        .map((content) => content.assignment_id) || []
    );

    // Filter assignments that are:
    // 1. In the current module
    // 2. Not associated with any topic
    // 3. Not closed
    const moduleAssignments = assignmentData.filter(
      (assignment) =>
        assignment.module_id === moduleId &&
        !topicAssociatedAssignmentIds.has(assignment.id) &&
        assignment.status !== "closed"
    );

    return moduleAssignments;
  };


  // Helper function to check if all topics in a module are completed
  const areAllTopicsCompleted = (moduleId) => {
    // topicData may be an array or object depending on how it's passed
    // Try both ways for robustness
    let topics = [];
    if (Array.isArray(topicData)) {
      topics = topicData.filter(t => t.module_id === moduleId);
    } else if (topicData?.data?.[0]?.data) {
      topics = topicData.data[0].data.filter(t => t.module_id === moduleId);
    }
    return topics.length > 0 && topics.every(t => completedTopics[t.id]);
  };

  // Check if a quiz has been completed
  const isQuizCompletedCheck = (quizId) => {
    if (!quizCompletionData) return false;

    return quizCompletionData.some(
      (completion) =>
        completion.quizId === quizId && completion.isCompleted === true && completion.status === "Passed"
    );
  };

  const isQuizCompletedCheckForFeedback = (quizId) => {
    if (!quizCompletionData) return false;

    return quizCompletionData.some(
      (completion) =>
        completion.quizId === quizId && completion.isCompleted === true
    );
  };

  // Check if an assignment has been completed
  const isAssignmentCompletedCheck = (assignmentId) => {
    if (!assignmentCompletionData) return false;
    return assignmentCompletionData.some(
      (completion) =>
        completion.assignmentId === assignmentId && completion.isCompleted
    );
  };

  // Add this new function to check if module is ready for feedback
  // const isModuleReadyForFeedback = (moduleId) => {
  //   // Guard clause: ensure all required data is available
  //   // if (!moduleId || !quizData || !topicData?.data?.[0]?.data) {
  //   //   return false;
  //   // }

  //   // Get all topics for this module
  //   const moduleTopics = topicData?.data?.[0]?.data?.filter(
  //     (topic) => topic.module_id === moduleId
  //   ) || [];

  //   // Get all quizzes for this module
  //   const moduleQuizzes = getModuleQuizzes(moduleId);

  //   // Check if all topics are completed (corrected logic)
  //   const allTopicsCompleted = moduleTopics.every((topic) => {
  //     if (completedTopics?.length > 0) {
  //       return completedTopics?.some((ct) => ct.topic_id === topic.id)
  //     }
  //     return false;
  //   });

  //   // Check if all quizzes have been attempted at least once
  //   // If there are no quizzes, we don't need to check quiz completion
  //   const allQuizzesAttempted = moduleQuizzes.length === 0 ? true : moduleQuizzes.every((quiz) => {
  //     const a = isQuizCompletedCheckForFeedback(quiz.id)
  //     return a;
  //   });

  //   return allTopicsCompleted && allQuizzesAttempted;
  // };

  return (
    <motion.div
      ref={sidebarRef}
      initial={{ width: sidebarCollapsed ? 80 : sidebarWidth }}
      animate={{ width: sidebarCollapsed ? 80 : sidebarWidth }}
      transition={{ type: "spring", stiffness: 300, damping: 30 }}
      className="bg-white overflow-y-auto relative shadow-lg text-gray-700 border-r border-gray-200 no-scrollbar z-10 sidebar-content h-full"
    >
      {/* Sidebar toggle button with improved positioning and styling */}
      <motion.div
        className="absolute right-1 top-6 z-20"
        animate={{
          x: sidebarCollapsed ? 1 : 0,
          rotate: sidebarCollapsed ? 180 : 0,
        }}
        transition={{ duration: 0.3 }}
      >
        <button
          className="bg-blue-500 hover:bg-blue-600 text-white p-2 rounded-full hover:shadow-lg transition-all duration-300 shadow-md"
          onClick={toggleSidebar}
          title={sidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"}
        >
          <FaChevronLeft className="w-4 h-4" />
        </button>
      </motion.div>

      {/* Expanded sidebar content */}
      {!sidebarCollapsed ? (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
          className="h-full flex flex-col"
        >
          {/* Enhanced course title header with glass morphism effect */}
          <div className="p-6 border-b border-gray-200 bg-gradient-to-r from-blue-50 to-indigo-50">
            <div className="flex items-center space-x-3">
              <div className="bg-gradient-to-br from-blue-600 to-indigo-700 p-3 rounded-lg shadow-md">
                <FaGraduationCap className="text-white h-6 w-6" />
              </div>
              <div className="flex-1 truncate">
                <h1 className="text-xl font-bold text-gray-800 truncate">
                  {courseTitle}
                </h1>
                <div className="flex items-center mt-1">
                  <div className="h-2 w-2 bg-green-400 rounded-full mr-2 animate-pulse"></div>
                  <p className="text-xs text-gray-500 font-medium">
                    {sessionsData?.sessions.length || 0}{" "}
                    {sessionsData?.sessions.length === 1
                      ? "session"
                      : "sessions"}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Sessions and modules list with improved spacing and animations */}
          <div className="flex-1 overflow-y-auto py-4 px-3 no-scrollbar">
            {sessionsData?.sessions.map((session, sessionIndex) => (
              <motion.div
                key={session.id || sessionIndex}
                className="mb-4"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: sessionIndex * 0.05 }}
              >
                <button
                  className={`flex items-center justify-between w-full px-4 py-3 text-left rounded-xl transition-all duration-300
                    ${activeSessionId === session.public_hash
                      ? "bg-gradient-to-r from-blue-100 to-indigo-100 text-blue-700 shadow-sm"
                      : "text-gray-600 hover:bg-gray-50 hover:text-blue-600"
                    }`}
                  onClick={() =>
                    setActiveSessionId(
                      activeSessionId === session.public_hash
                        ? null
                        : session.public_hash
                    )
                  }
                >
                  <div className="flex items-center min-w-0">
                    <motion.span
                      className={`flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-lg mr-3 transition-all shadow-sm
                        ${activeSessionId === session.public_hash
                          ? "bg-gradient-to-br from-blue-500 to-indigo-600 text-white"
                          : "bg-gray-100 text-gray-600"
                        }`}
                      whileHover={{ scale: 1.05 }}
                      transition={{
                        type: "spring",
                        stiffness: 400,
                        damping: 10,
                      }}
                    >
                      <FaBookOpen className="w-4 h-4" />
                    </motion.span>
                    <span className="font-medium truncate">
                      {session.title || `Session ${sessionIndex + 1}`}
                    </span>
                  </div>
                  <motion.span
                    className="text-lg ml-2 flex-shrink-0"
                    animate={{
                      rotate: activeSessionId === session.public_hash ? 180 : 0,
                    }}
                    transition={{ duration: 0.3 }}
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <polyline points="6 9 12 15 18 9"></polyline>
                    </svg>
                  </motion.span>
                </button>

                {/* Modules within session - with improved spacing and visual hierarchy */}
                {activeSessionId === session.public_hash && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    transition={{ duration: 0.3 }}
                    className="pl-5 mt-3"
                  >
                    {modules
                      .filter((module) => module.session_id === session.id)
                      .map((module, moduleIndex) => (
                        <motion.div
                          key={module.id}
                          className={`mb-3`}
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          transition={{
                            duration: 0.3,
                            delay: moduleIndex * 0.05,
                          }}
                        >
                          {/* Module with progress indicator */}
                          <div className="relative">
                            <EnhancedButton
                              isLocked={!module.isAccessible}
                              isCompleted={completedModules[module.id]}
                              isActive={activeModuleId === module.public_hash}
                              type="module"
                              onClick={() => {
                                if (module.isAccessible) {
                                  setActiveModuleId(
                                    activeModuleId === module.public_hash
                                      ? null
                                      : module.public_hash
                                  );
                                  setNewModuleId(
                                    activeModuleId === module.public_hash
                                      ? null
                                      : module.id
                                  );
                                }
                              }}
                            >
                              {module.title || `Module ${moduleIndex + 1}`}
                            </EnhancedButton>

                            {/* Lock icon overlay for inaccessible modules */}
                            {!module.isAccessible && (
                              <div className="absolute right-3 top-1/2 -translate-y-1/2 text-amber-500">
                                <FaLock className="w-4 h-4" />
                              </div>
                            )}
                          </div>

                          {/* Topics within module - improved design and restrictions */}
                          {activeModuleId === module.public_hash && (
                            <motion.div
                              initial={{ height: 0, opacity: 0 }}
                              animate={{ height: "auto", opacity: 1 }}
                              transition={{ duration: 0.3 }}
                              className="pl-5 mt-3 border-l-2 border-gray-100 ml-4 overflow-hidden"
                            >
                              {/* Topics section header */}
                              <div className="mb-2 px-3">
                                <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
                                  Topics
                                </span>
                              </div>

                              {/* Topics list */}
                              {topicData?.map((topic, topicIndex) => (
                                <div key={topic.id} className="relative mb-2">
                                  {/* Topic Title with improved styling */}
                                  <EnhancedButton
                                    isLocked={!topic.isAccessible}
                                    type={topic.content_type}
                                    isCompleted={isTopicCompleted(topic.id)}
                                    onClick={() =>
                                      topic.isAccessible &&
                                      handleTopicClick(topic)
                                    }
                                    isActive={activeTopic?.id === topic.id}
                                  >
                                    {topic.title}
                                  </EnhancedButton>

                                  {/* Topic Content with improved styling */}
                                  {(getTopicQuizzes(topic.id).length > 0 ||
                                    getTopicAssignments(topic.id).length > 0) &&
                                    activeTopic?.id === topic.id && (
                                      <motion.div
                                        initial={{ height: 0, opacity: 0 }}
                                        animate={{ height: "auto", opacity: 1 }}
                                        transition={{ duration: 0.3 }}
                                        className="pl-4 mt-2 border-l-2 border-gray-100 ml-4 overflow-hidden"
                                      >
                                        {/* Topic Quizzes Section */}
                                        {getTopicQuizzes(topic.id).length > 0 && (
                                          <>
                                            <div className="text-xs text-gray-500 px-3 py-1">
                                              {getTopicQuizzes(topic.id).length > 1 ? "Quizzes" : "Quiz"}
                                            </div>
                                            {getTopicQuizzes(topic.id).map(
                                              (quiz, index) => {
                                                const topicComplete = isTopicCompleted(topic.id);
                                                const isComplete = isQuizCompletedCheck(quiz.id);
                                                const isActive =
                                                  activeTopicMaterial.id === quiz.id &&
                                                  activeTopicMaterial.type === "quiz";

                                                return (
                                                  <motion.div
                                                    key={quiz.id}
                                                    className="relative"
                                                    onMouseEnter={() =>
                                                      !topicComplete &&
                                                      setShowTooltip(`quiz-${quiz.id}`)
                                                    }
                                                    onMouseLeave={() =>
                                                      setShowTooltip(null)
                                                    }
                                                  >
                                                    <motion.button
                                                      className={`w-full px-3 py-2 my-1 text-sm transition-all duration-300 rounded-lg flex items-center group ${!topicComplete
                                                        ? "bg-gray-50 text-gray-400 cursor-not-allowed opacity-70"
                                                        : isActive
                                                          ? "bg-blue-100 text-blue-700 border-l-2 border-blue-500"
                                                          : "text-gray-600 hover:bg-blue-50 hover:text-blue-600"
                                                        }`}
                                                      onClick={() => {
                                                        if (topicComplete) {
                                                          const fullQuiz = quizData.find(
                                                            (q) => q.id === quiz.id
                                                          );
                                                          if (fullQuiz) {
                                                            handleModuleQuizClick(
                                                              fullQuiz,
                                                              "topicMaterial"
                                                            );
                                                          }
                                                        }
                                                      }}
                                                      disabled={!topicComplete}
                                                      initial={{
                                                        opacity: 0,
                                                        x: -10,
                                                      }}
                                                      animate={{ opacity: 1, x: 0 }}
                                                      transition={{
                                                        delay: index * 0.1,
                                                      }}
                                                    >
                                                      <div className="flex items-center w-full min-w-0">
                                                        <motion.span
                                                          className={`flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-md text-xs mr-2 transition-all duration-300 shadow-sm ${isComplete
                                                            ? "bg-green-100 text-green-600"
                                                            : isActive
                                                              ? "bg-blue-500 text-white"
                                                              : !topicComplete
                                                                ? "bg-gray-100 text-gray-400"
                                                                : "bg-blue-100 text-blue-600"
                                                            }`}
                                                          whileHover={{
                                                            scale: topicComplete
                                                              ? 1.1
                                                              : 1,
                                                          }}
                                                          transition={{
                                                            type: "spring",
                                                            stiffness: 400,
                                                            damping: 10,
                                                          }}
                                                        >
                                                          {isComplete ? (
                                                            <FaCheckCircle className="w-3 h-3" />
                                                          ) : (
                                                            <FaQuestionCircle className="w-3 h-3" />
                                                          )}
                                                        </motion.span>
                                                        <span
                                                          className={`truncate text-left text-xs flex-1 min-w-0 ${isActive
                                                            ? "font-semibold"
                                                            : ""
                                                            }`}
                                                        >
                                                          {quiz.title}
                                                        </span>

                                                        {/* Status indicator */}
                                                        {isComplete && (
                                                          <span className="ml-2 bg-green-100 text-green-600 text-xs px-2 py-0.5 rounded-full">
                                                            Completed
                                                          </span>
                                                        )}

                                                        {!topicComplete && (
                                                          <FaLock className="w-3 h-3 text-gray-400 ml-1" />
                                                        )}
                                                      </div>
                                                    </motion.button>

                                                    {/* Tooltip for locked quizzes */}
                                                    {showTooltip ===
                                                      `quiz-${quiz.id}` &&
                                                      !topicComplete && (
                                                        <div className="absolute z-50 w-52 bg-white shadow-lg rounded-md p-2 text-xs border border-gray-200 left-full ml-2 top-0">
                                                          <div className="flex items-start p-1">
                                                            <div className="bg-amber-100 rounded-full p-1 mr-2">
                                                              <FaLock className="text-amber-600 w-3 h-3" />
                                                            </div>
                                                            <div>
                                                              <p className="font-medium text-gray-800">
                                                                Quiz Locked
                                                              </p>
                                                              <p className="text-gray-600 mt-1">
                                                                Complete the topic
                                                                to access this quiz.
                                                              </p>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      )}
                                                  </motion.div>
                                                );
                                              }
                                            )}
                                          </>
                                        )}

                                        {/* Topic Assignments Section */}
                                        {getTopicAssignments(topic.id).length > 0 && (
                                          <>
                                            <div className="text-xs text-gray-500 px-3 py-1">
                                              {getTopicAssignments(topic.id).length > 1 ? "Assignments" : "Assignment"}
                                            </div>
                                            {getTopicAssignments(topic.id).map(
                                              (assignment, index) => {
                                                const topicComplete = isTopicCompleted(topic.id);
                                                const isComplete = isAssignmentCompletedCheck(
                                                  assignment.id
                                                );
                                                const isActive =
                                                  activeTopicMaterial.id === assignment.id &&
                                                  activeTopicMaterial.type === "assignment";

                                                return (
                                                  <motion.div
                                                    key={assignment.id}
                                                    className="relative"
                                                    onMouseEnter={() =>
                                                      !topicComplete &&
                                                      setShowTooltip(
                                                        `assignment-${assignment.id}`
                                                      )
                                                    }
                                                    onMouseLeave={() =>
                                                      setShowTooltip(null)
                                                    }
                                                  >
                                                    <motion.button
                                                      className={`w-full px-3 py-2 my-1 text-sm transition-all duration-300 rounded-lg flex items-center group ${!topicComplete
                                                        ? "bg-gray-50 text-gray-400 cursor-not-allowed opacity-70"
                                                        : isActive
                                                          ? "bg-green-100 text-green-700 border-l-2 border-green-500"
                                                          : "text-gray-600 hover:bg-green-50 hover:text-green-600"
                                                        }`}
                                                      onClick={() => {
                                                        if (topicComplete) {
                                                          const fullAssignment =
                                                            assignmentData.find(
                                                              (a) =>
                                                                a.id ===
                                                                assignment.id
                                                            );
                                                          if (fullAssignment) {
                                                            handleModuleAssignmentClick(
                                                              fullAssignment,
                                                              "topicMaterial"
                                                            );
                                                          }
                                                        }
                                                      }}
                                                      disabled={!topicComplete}
                                                      initial={{
                                                        opacity: 0,
                                                        x: -10,
                                                      }}
                                                      animate={{ opacity: 1, x: 0 }}
                                                      transition={{
                                                        delay:
                                                          (getTopicQuizzes(topic.id)
                                                            .length +
                                                            index) *
                                                          0.1,
                                                      }}
                                                    >
                                                      <div className="flex items-center w-full min-w-0">
                                                        <motion.span
                                                          className={`flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-md text-xs mr-2 transition-all duration-300 shadow-sm
                ${isComplete
                                                              ? "bg-green-100 text-green-600"
                                                              : isActive
                                                                ? "bg-blue-500 text-white"
                                                                : !topicComplete
                                                                  ? "bg-gray-100 text-gray-400"
                                                                  : "bg-blue-100 text-blue-600"
                                                            }`}
                                                          whileHover={{
                                                            scale: topicComplete
                                                              ? 1.1
                                                              : 1,
                                                          }}
                                                          transition={{
                                                            type: "spring",
                                                            stiffness: 400,
                                                            damping: 10,
                                                          }}
                                                        >
                                                          {isComplete ? (
                                                            <FaCheckCircle className="w-3 h-3" />
                                                          ) : (
                                                            <FaPencilAlt className="w-3 h-3" />
                                                          )}
                                                        </motion.span>
                                                        <span
                                                          className={`truncate text-left text-xs flex-1 min-w-0 ${isActive
                                                            ? "font-semibold"
                                                            : ""
                                                            }`}
                                                        >
                                                          {assignment.title}
                                                        </span>

                                                        {/* Status indicator */}
                                                        {isComplete && (
                                                          <span className="ml-2 bg-green-100 text-green-600 text-xs px-2 py-0.5 rounded-full">
                                                            Completed
                                                          </span>
                                                        )}

                                                        {/* Locked indicator */}
                                                        {!topicComplete && (
                                                          <FaLock className="w-3 h-3 text-gray-400 ml-1" />
                                                        )}
                                                      </div>
                                                    </motion.button>

                                                    {/* Tooltip for locked assignments */}
                                                    {showTooltip ===
                                                      `assignment-${assignment.id}` &&
                                                      !topicComplete && (
                                                        <div className="absolute z-50 w-52 bg-white shadow-lg rounded-md p-2 text-xs border border-gray-200 left-full ml-2 top-0">
                                                          <div className="flex items-start p-1">
                                                            <div className="bg-amber-100 rounded-full p-1 mr-2">
                                                              <FaLock className="text-amber-600 w-3 h-3" />
                                                            </div>
                                                            <div>
                                                              <p className="font-medium text-gray-800">
                                                                Assignment Locked
                                                              </p>
                                                              <p className="text-gray-600 mt-1">
                                                                Complete the topic
                                                                to access this
                                                                assignment.
                                                              </p>
                                                            </div>
                                                          </div>
                                                        </div>
                                                      )}
                                                  </motion.div>
                                                );
                                              }
                                            )}
                                          </>
                                        )}
                                      </motion.div>
                                    )}
                                </div>
                              ))}

                              {/* Module Quizzes Section with improved grouping */}
                              {getModuleQuizzes(module.id).length > 0 && (
                                <motion.div
                                  initial={{ opacity: 0, y: 10 }}
                                  animate={{ opacity: 1, y: 0 }}
                                  transition={{ duration: 0.3 }}
                                  className="mt-4 pt-3 border-t border-gray-100"
                                >
                                  {/* Section header */}
                                  <div className="mb-2 px-3">
                                    <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
                                      Module Quizzes
                                    </span>
                                  </div>

                                  {/* Module quiz list */}
                                  {getModuleQuizzes(module.id).map(
                                    (quiz, index) => {
                                      const isComplete = isQuizCompletedCheck(
                                        quiz.id
                                      );
                                      const locked = !areAllTopicsCompleted(module.id);
                                      return (
                                        <motion.button
                                          key={quiz.id}
                                          className={`w-full px-3 py-2.5 my-1 text-sm transition-all duration-300 rounded-lg flex items-center group relative text-gray-600 hover:bg-blue-50 hover:text-blue-600 ${locked ? "cursor-not-allowed opacity-60" : ""}`}
                                          onClick={() =>
                                            !locked && handleModuleQuizClick(
                                              quiz,
                                              "moduleMaterial"
                                            )
                                          }
                                          disabled={locked}
                                          initial={{ opacity: 0, x: -10 }}
                                          animate={{ opacity: 1, x: 0 }}
                                          transition={{ delay: index * 0.1 }}
                                        >
                                          <div className="flex items-center w-full min-w-0">
                                            <motion.span
                                              className={`flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-md text-xs mr-2 transition-all duration-300 shadow-sm
                                              ${isComplete
                                                  ? "bg-green-100 text-green-600"
                                                  : "bg-blue-100 text-blue-600"
                                                }`}
                                              whileHover={{ scale: 1.1 }}
                                              transition={{
                                                type: "spring",
                                                stiffness: 400,
                                                damping: 10,
                                              }}
                                            >
                                              {isComplete ? (
                                                <FaCheckCircle className="w-3 h-3" />
                                              ) : (
                                                <FaQuestionCircle className="w-3 h-3" />
                                              )}
                                            </motion.span>
                                            <span className="truncate text-left text-xs flex-1 min-w-0 font-medium">
                                              {quiz.title}
                                            </span>

                                            {/* Status indicator */}
                                            {isComplete && (
                                              <span className="ml-2 bg-green-100 text-green-600 text-xs px-2 py-0.5 rounded-full">
                                                Completed
                                              </span>
                                            )}
                                            {locked && <FaLock className="ml-2 text-gray-400" />}
                                          </div>
                                        </motion.button>
                                      );
                                    }
                                  )}
                                  {/* Tooltip/message for locked state */}
                                  {!areAllTopicsCompleted(module.id) && (
                                    <div className="text-xs text-gray-500 mt-1 text-center">
                                      Complete all topics to unlock module quizzes
                                    </div>
                                  )}
                                </motion.div>
                              )}

                              {/* Module Assignments Section with improved UI */}
                              {getModuleAssignments(module.id).length > 0 && (
                                <motion.div
                                  initial={{ opacity: 0, y: 10 }}
                                  animate={{ opacity: 1, y: 0 }}
                                  transition={{ duration: 0.3 }}
                                  className="mt-4 pt-3 border-t border-gray-100"
                                >
                                  {/* Section header */}
                                  <div className="mb-2 px-3">
                                    <span className="text-xs font-semibold uppercase tracking-wider text-gray-500">
                                      Module Assignments
                                    </span>
                                  </div>

                                  {/* Assignment list */}
                                  {getModuleAssignments(module.id).map(
                                    (assignment, index) => {
                                      const isComplete =
                                        isAssignmentCompletedCheck(
                                          assignment.id
                                        );
                                      const locked = !areAllTopicsCompleted(module.id);
                                      return (
                                        <motion.button
                                          key={assignment.id}
                                          className={`w-full px-3 py-2.5 my-1 text-sm transition-all duration-300 rounded-lg flex items-center group relative text-gray-600 hover:bg-green-50 hover:text-green-600 ${locked ? "cursor-not-allowed opacity-60" : ""}`}
                                          onClick={() =>
                                            !locked && handleModuleAssignmentClick(
                                              assignment,
                                              "moduleMaterial"
                                            )
                                          }
                                          disabled={locked}
                                          initial={{ opacity: 0, x: -10 }}
                                          animate={{ opacity: 1, x: 0 }}
                                          transition={{ delay: index * 0.1 }}
                                        >
                                          <div className="flex items-center w-full min-w-0">
                                            <motion.span
                                              className={`flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-md text-xs mr-2 transition-all duration-300 shadow-sm ${isComplete
                                                ? "bg-green-100 text-green-600"
                                                : "bg-blue-500 text-white"
                                                }`}
                                              whileHover={{ scale: 1.1 }}
                                              transition={{
                                                type: "spring",
                                                stiffness: 400,
                                                damping: 10,
                                              }}
                                            >
                                              {isComplete ? (
                                                <FaCheckCircle className="w-3 h-3" />
                                              ) : (
                                                <FaFileAlt className="w-3 h-3" />
                                              )}
                                            </motion.span>
                                            <span className="truncate text-left text-xs flex-1 min-w-0 font-medium">
                                              {assignment.title}
                                            </span>

                                            {/* Status indicator */}
                                            {isComplete && (
                                              <span className="ml-2 bg-green-100 text-green-600 text-xs px-2 py-0.5 rounded-full">
                                                Completed
                                              </span>
                                            )}
                                            {locked && <FaLock className="ml-2 text-gray-400" />}
                                          </div>
                                        </motion.button>
                                      );
                                    }
                                  )}
                                  {/* Tooltip/message for locked state */}
                                  {!areAllTopicsCompleted(module.id) && (
                                    <div className="text-xs text-gray-500 mt-1 text-center">
                                      Complete all topics to unlock module assignments
                                    </div>
                                  )}
                                </motion.div>
                              )}

                              {/* Add the feedback button with conditional rendering */}
                              <div className="mt-4 px-4">
                                <button
                                  onClick={() => {
                                    setShowFeedback(true);
                                    setSelectedModuleId(module.id);
                                  }}
                                  disabled={!isModuleReadyForFeedback(module.id, topicData, quizData, completedTopics, quizCompletionData) || shouldAutoGenerateFeedback}
                                  className={`w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition-all duration-300 ${isModuleReadyForFeedback(module.id, topicData, quizData, completedTopics, quizCompletionData) && !shouldAutoGenerateFeedback
                                    ? "bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-500 hover:to-amber-600 text-white shadow-md hover:shadow-lg"
                                    : "bg-gray-100 text-gray-400 cursor-not-allowed"
                                    }`}
                                >
                                  {shouldAutoGenerateFeedback ? (
                                    <>
                                      <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></div>
                                      <span>Generating Feedback...</span>
                                    </>
                                  ) : (
                                    <>
                                      <FaLightbulb className="text-lg" />
                                      <span>Show Feedback</span>
                                    </>
                                  )}
                                </button>
                                {!isModuleReadyForFeedback(module.id, topicData, quizData, completedTopics, quizCompletionData) && (
                                  <p className="text-xs text-gray-500 mt-1 text-center">
                                    Complete all topics and attempt all quizzes to unlock feedback
                                  </p>
                                )}
                                {shouldAutoGenerateFeedback && (
                                  <p className="text-xs text-blue-500 mt-1 text-center">
                                    Auto-generating your first feedback...
                                  </p>
                                )}
                              </div>
                            </motion.div>
                          )}
                        </motion.div>
                      ))}
                  </motion.div>
                )}
              </motion.div>
            ))}
          </div>

          {/* Enhanced End Session Button */}
          <div className="mt-auto p-4 border-t border-gray-200 bg-gradient-to-r from-gray-50 to-gray-100">
            <button
              onClick={() => setShowEndSessionModal(true)}
              className="flex items-center justify-center w-full py-2.5 px-4 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-xl transition-all duration-300 hover:from-red-600 hover:to-red-700 hover:shadow-md font-medium"
            >
              <FaSignOutAlt className="mr-2" />
              End Session
            </button>
          </div>
        </motion.div>
      ) : (
        <motion.div
          className="flex flex-col items-center pt-16 space-y-6 h-full"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
        >
          <motion.div
            className="bg-gradient-to-br from-blue-600 to-indigo-700 p-3 rounded-lg shadow-md"
            whileHover={{ scale: 1.1, rotate: 5 }}
            transition={{ type: "spring", stiffness: 400, damping: 10 }}
          >
            <FaGraduationCap className="text-white h-5 w-5" />
          </motion.div>

          {sessionsData?.sessions.map((session, index) => (
            <motion.button
              key={session.id || index}
              className={`w-10 h-10 flex items-center justify-center rounded-lg cursor-pointer transition-all duration-300 shadow-md
                ${activeSessionId === session.public_hash
                  ? "bg-gradient-to-br from-blue-500 to-indigo-600 text-white"
                  : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                }`}
              title={session.title || `Session ${index + 1}`}
              onClick={() => setActiveSessionId(session.public_hash)}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.95 }}
            >
              <FaBookOpen className="w-4 h-4" />
            </motion.button>
          ))}

          <motion.button
            onClick={() => setShowEndSessionModal(true)}
            className="w-10 h-10 flex items-center justify-center rounded-lg bg-gradient-to-br from-red-500 to-red-600 text-white hover:from-red-600 hover:to-red-700 transition-all duration-300 shadow-md mt-auto mb-6"
            title="End Session"
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.95 }}
          >
            <FaSignOutAlt />
          </motion.button>
        </motion.div>
      )}

      {/* Feedback Modal */}
      {showFeedback && (
        <FeedBackModal
          userId={userId}
          moduleId={selectedModuleId}
          isOpen={showFeedback}
          onClose={() => {
            setShowFeedback(false);
            setSelectedModuleId(null);
            setShouldAutoGenerateFeedback(false);
            setHasAutoGeneratedFeedback(false);
          }}
          isAutoGenerating={shouldAutoGenerateFeedback}
        />
      )}
    </motion.div>
  );
};

export default CourseSidebar;
